### ISSUE TITLE
package.xml is missing from qt_create in Ubuntu

### ISSUE THREAD

**Issue by ghost** [stonier/qt_ros#7]
The file "package.xml" is not present in Ubuntu's package of "ros-hydro-qt-create". When trying to run "catkin_create_qt_pkg" to generate a new ROS package from the template, the Python script fails complaining that the file can not be found (yet it is present in the Git repository).

Details can be found here: http://answers.ros.org/question/117596/catkin_create_qt_pkg-fails-packagexml-not-found/

**Comment by stonier** [comment]
Fixed in 8a6bc5012374b111c39c4f746a6abea8622ab9b0.

0.2.3 has been released to the build farm. They are doing a sync this weekend, so it might get in straight away, but if it doesn't, just copy [package.xml](https://github.com/stonier/qt_ros/blob/hydro/qt_create/src/qt_create/templates/qt-ros/package.xml) into the location specified by the error.

Thanks for letting us know about this!

**Comment by ghost** [comment]
Great!
